language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t lucasbaier/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lucasbaier/docker-react npm run test  